### PR TITLE
More user-friendly !uptime output

### PR DESCRIPTION
**Pull request by CylonicRaider**
Fractional hours aren't exactly very readable...

### CODE REVIEW

**Comment by ckingdev** [comment]
Take a look here - http://golang.org/pkg/time/#Duration

Seconds and Minutes are total counts, so this will display an incorrect time. You can just do the same thing you did for days and hours, though.

**Comment by ckingdev** [comment]
Also, please rebase against master.

**Comment by CylonicRaider** [comment]
How do you define an "awfully long line"?

**Comment by ckingdev** [comment]
In my mind there's gotta be a good reason to go over 80 characters, and there's almost never any reason to go over 100 characters. That line is 179 characters.

For context, I often view files side by side on a 1080p screen. This keeps me from having to scroll unnecessarily and helps especially if someone needs to view the file on the command line.

**Comment by CylonicRaider** [comment]
Well, the other lines I looked at for comparison seemed not to care about length.

**Comment by ckingdev** [comment]
I'm still cleaning up the codebase. You'll see those disappear in the next few days.

**Comment by CylonicRaider** [comment]
So, 80 or 100?

**Comment by ckingdev** [comment]
Get it to under 100, I'll take care of any other formatting I want to do when I make a pass through the codebase for this stuff. Thanks!

**Comment by ckingdev** [comment]
Thanks!

**Pull request merged**
